### ISSUE TITLE
make sure I understand `structured_pattern`'s   `interpolated` and `partial_match` options

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/mixs-6-2-release-candidate#149]
see also
- #146
- #147 
- #148

**Comment by turbomam** [comment]
Assertions like this are working well
```yaml
    structured_pattern:
      syntax: ^{scientific_float}( *- *{scientific_float})? *{text}$
      interpolated: true
      partial_match: true
```

as long as the syntax contains the ^ and $ anchors. Anchors should not be included in the settings, like 
`scientific_float: "[-+]?[0-9]*\\.?[0-9]+(?:[eE][-+]?[0-9]+)?"`
