### ISSUE TITLE
Do we want slots like `farm_equip` to be validated against the term label/term id syntax, or the AGRO:00000416 parent class?

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/mixs-6-2-release-candidate#172]
see also
- #171

**Comment by turbomam** [comment]
For example, config/linkml-stage-mixs-modifications.yaml can assert that slot `farm_equip` has `range` of `FARM_EQUIP_ENUM`, which can be defined as

```yaml
  FARM_EQUIP_ENUM:
    reachable_from:
      source_ontology: obo:agro
      source_nodes:
        - AGRO:00000416
      relationship_types:
        - rdfs:subClassOf
      is_direct: False
      include_self: False
      traverse_up: False
```

then, using the prototype `vskit` command in `project.Makefile`, `FARM_EQUIP_ENUM` will have the class IDs of subclasses of  AGRO:00000416 assigned as `permissible_values`.

At that point, AGRO:00000676 would be an acceptable value for `farm_equip`, but  values in the traditional pattern like "feed pan [AGRO:00000676]" wouldn't be
