### ISSUE TITLE
slots not present in curated-data/build-test-only/AllSlotsTestClassCollection-wrapped-example-data.yaml

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/mixs-6-2-release-candidate#178]
see other-reports/build-test-data-coverage-report.yaml

```yaml
optional_not_present:
- physical_sex
- soil_text_measure
- texture
recommended_not_present:
- soil_depth
```
